function [scenario, egoVehicle] = createDrivingScenario()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.12 (R2022a) and Automated Driving Toolbox 3.5 (R2022a).
% Generated on: 18-Dec-2023 15:59:40

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [0 -0.1 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [0 -0.1 0;
    10.3 -0.1 0;
    20.3 -0.1 0;
    30 -0.3 0;
    40.1 -10.2 0;
    39.9 -19.9 0;
    40 -29.2 0];
speed = [10;10;10;10;10;10;10];
smoothTrajectory(egoVehicle, waypoints, speed);
figure
plot(waypoints(:,1),waypoints(:,2),'-o')
xlabel('X (m)')
ylabel('Y (m)')
title('Vehicle Position Waypoints')

